#!/usr/bin/env ruby

require 'slop'

opts = Slop.parse do |o|
    o.integer '-p', '--port',
              "The port to run the server on (default: 8000)",
               default: 8000
    o.on '-h', '--help' do
        puts o
        exit
    end
end

# Replace current process
exec "php -S localhost:#{opts[:port]}"
