#!/usr/bin/env ruby

require 'fileutils'
require 'slop'

OPTS = Slop.parse do |o|
    o.bool '-d', '--dry-run', "Don't actually rename anything", default: false
    o.bool '--only-movies', "Rename only movies", default: false
    o.bool '--only-tv', "Rename only TV shows", default: false
    o.on '-h', '--help', "Prints this message" do
        puts o
        exit
    end
end

exts = [
    "mp4",
    "mkv"
]

def scan_movies
    OPTS.only_movies? || !OPTS.only_tv?
end

def scan_tv
    OPTS.only_tv? || !OPTS.only_movies?
end

def is_clean_movie(name)
    !name.match(/\[\d{4}\]/).nil?
end

def clean_name(name)
    name.gsub(/[.]/, ' ').gsub(/[\[\]\-\{\}]/, ' ').gsub(/ +$/, '')
end

exts.each do |ext|
    Dir.glob("**/*.#{ext}").each do |filename|
        dir  = File.dirname(filename)
        file = File.basename(filename)

        new_filename = nil

        if scan_tv
            # TV Show?
            m = file.match /^(.+?)(S\d{2}E\d{2})/
            unless m.nil?
                name   = clean_name(m[1])
                serial = m[2]

                new_filename = "#{name} - #{serial}.#{ext}"
            end
        end

        # Movie?
        if scan_movies
            m = file.match /^(.+?)(\d{4})/
            if new_filename.nil? && !m.nil? && !is_clean_movie(file)
                name = clean_name(m[1])
                year = m[2]

                new_filename = "#{name} [#{year}].#{ext}"
            end
        end

        # Rename the file
        unless new_filename.nil? || (filename == new_filename)
            if OPTS.dry_run?
                puts "#{filename} => #{new_filename}"
            else
                FileUtils.mv(filename, new_filename)
            end
        end

        # Only trash the folder if it's not the current one
        unless dir == "." || OPTS.dry_run?
            FileUtils.mv(dir, "#{ENV['HOME']}/.Trash/")
        end
    end
end
