#!/usr/bin/env ruby

require 'slop'

opts = Slop.parse do |o|
    o.bool '-a', '--all', "Include dotfiles", default: false
    o.integer '-l', '--level', "The level to which to traverse (default: 0)", default: 0
    o.on '-h', '--help' do
        puts o
        exit
    end
end

system("sudo du -h #{(opts.all? ? "-a" : "")} -d #{opts[:level]} *")
