#!/usr/bin/env ruby

version_filename = "ProjectSettings/ProjectVersion.txt"
version_file     = File.expand_path(version_filename)

unless File.exists? version_file
    raise "#{version_filename} doesn't exist in this directory!"
    exit 1
end

contents = File.read(version_file)

puts "Version: " + contents.split("\n").first.chomp.gsub("m_EditorVersion: ", "")