#!/usr/bin/env ruby

if ARGV[0].match(/help/)
    puts "\nUsage:"
    puts "    ❯ unlock-pdf password files"
    exit 0
end

files = ARGV.dup
password = files.shift

cmd = "qpdf"
options = "--decrypt --password=#{password} --replace-input"

files.each do |filename|
    print "Unlocking #{filename}..."
    %x(#{cmd} #{filename.inspect} #{options})
    puts "Done."
end

puts "All Done."
